### ISSUE TITLE
Hits randomly launch victim upwards, even when not configured to (possibly related to potion effects?)

### ISSUE THREAD

**Issue by nebula161** [CivMC/Finale#15]
Maybe related to #14

**Comment by Aleksey-Terzi** [comment]
I don't think the victim is launched upwards.
Most probably this is the attacker who is launched.
We increase the attacker's velocity on the attack at the time when it should be decreased.
The original Minecraft code decreases the attacker's velocity by 40%.
This happens randomly because the change we do can be applied only when the server sends the request to the client though this doesn't happen always but only at some specific events.

PR #23 should fix the issue: https://github.com/CivMC/Finale/pull/23/commits/50e22a5adc71f6d3398864f93c270ae4364bfb2e

**Comment by Aleksey-Terzi** [comment]
I would remove `attackerMotion `from the config at all and used the constant vector (0.6, 1, 0.6)

**Comment by Diet-Cola** [comment]
Fixed from #23
